### ISSUE TITLE
write a content

### ISSUE THREAD

**Issue by lexoyo** [silexlabs/hn#1]
we need a content in FR/EN to say
* what is our meetup
* who we expect
* who we are
* date + time + place

**Comment by ghost** [comment]
https://hn.silexlabs.org/
Any comment about the homepage?

**Comment by lexoyo** [comment]
it is nice!
not responsive though but I like it anyway :+1:

**Comment by ghost** [comment]
> not responsive though but I like it anyway

Should be as everything is 100% width.
